### ISSUE TITLE
from markovbot import MarkovBot fails

### ISSUE THREAD

**Issue by mikeportanova** [esdalmaijer/markovbot#10]
As the subject says, after installing with pip, markovbot indicates it lacks MarkovBot in python 3.5

**Comment by mikeportanova** [comment]
![image](https://cloud.githubusercontent.com/assets/6099828/24385014/9cd4f490-1335-11e7-9cb8-29fdc62dbb2d.png)

This should not fail, but does. I have tried importing the class directly and that also fails.

**Comment by alanbaumgartner** [comment]
@mikeportanova I am having this issue as well, did you ever find a fix?
