### ISSUE TITLE
Missing database in Markovbot._autoreply

### ISSUE THREAD

**Issue by james-nichols** [esdalmaijer/markovbot#2]
`MSG from Markovbot._autoreply: James Nichols (@james_nichols): .@MalcolmTurnbot What do you think about agility? #HeyTurnbot
MSG from Markovbot._autoreply: I found seedwords: '['agility']'.
Exception in thread autoreplier:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/james/projects/malcolm_turnbot/markovbot/markovbot.py", line 888, in _autoreply
    response = self._construct_tweet(database=database, \
UnboundLocalError: local variable 'database' referenced before assignment
`
Normal auto-tweeting works fine, so a database certainly is in there. Looking in to it now to suggest fix. PS thanks for the excellent Markov generator!

**Comment by esdalmaijer** [comment]
Woops, that's my bad! For a temporary fix, change your call to `twitter_autoreply_start` to include `database=u'auto-language'` keyword. Example:

``` .python
tweetbot.twitter_autoreply_start(targetstring, database=u'auto-language', keywords=None, prefix=None, suffix=None, maxconvdepth=None, mindelay=1.5)
```

Thanks for the compliment! Great to see people are using it :)

**Comment by esdalmaijer** [comment]
TODO: Add the following to complete the if statement that starts on [line 828](https://github.com/esdalmaijer/markovbot/blob/master/markovbot/markovbot.py#L828):

``` .python
else:
    database = self._autoreply_database
```

**Comment by esdalmaijer** [comment]
This issue should be solved by the latest [commit](https://github.com/esdalmaijer/markovbot/commit/563919f1e95bf2ff03f65de840e6dea480beea62). Would you mind downloading the newest code, and checking whether it works?
