### ISSUE TITLE
Feature request - random selection of suffix and prefix

### ISSUE THREAD

**Issue by WilliamSGodfrey** [esdalmaijer/markovbot#3]
Edwin, this is a great little utility. Thanks.

Would it be possible to pass a list of strings to `twitter_autoreply_start` and `twitter_tweeting_start` for `suffix=` and `prefix=` such that a random item from the list would be used?

**Comment by esdalmaijer** [comment]
Thanks for the compliment!

The feature you requested should be available from the [latest commit](https://github.com/esdalmaijer/markovbot/commit/16c355ba5b6f3b38b9390a53eec985b145a2285b). Would you mind downloading and testing the new code, please?
