### ISSUE TITLE
Hi can I run multiple keyword listeners in the same bot??

### ISSUE THREAD

**Issue by trismegistis** [esdalmaijer/markovbot#4]
Seems like its not picking up my keywords with multiple "tweetbot.twitter_autoreply_start(" functions called..

**Comment by esdalmaijer** [comment]
That's right, the function signals an existing Thread what to do; it doesn't launch a new one with new parameters. There are two ways to make your bot reply to multiple keywords:
1. Combine multiple search keywords into a single string. This will make your auto-replier reply to all of the search keywords by using the same library/libraries (or using different languages; it depends on what you passed to the `twitter_autoreply_start` method). The Twitter dev site gives a great explanation [here](https://dev.twitter.com/streaming/overview/request-parameters#track). In short, you can use `'foo bar'` to auto-reply only when `'foo'` AND `'bar'` appear in a tweet together, or you can use `'foo, bar'` to auto-reply to tweets that contain `'foo'` OR `'bar'`.
2. You could start multiple instances of MarkovBot, each with their own specific auto-reply parameters.

**Comment by trismegistis** [comment]
Awesome! Thanks. I got my test account banned because I made multiple scripts to listen to each and every keyword, and they started conflicting xD

**Comment by esdalmaijer** [comment]
Hahaha, woops! Yeah, you have to respect Twitter's post limits. Also, spamming random Twitter users is not cool, so keep the auto-replying within limits ;)

(PS: Closing the issue, as it's resolved. Please do open a new one if you need anything else.)
